Проект
Garik77770/Project pull request #1
Opened 2022-04-01 11:01 UTC by Garik77770

Project 1 ur

2022-04-01 13:39 UTC, DenVilk requested changes
В файле Workshop должен быть класс Workshop кроме этого класса ничего больше не может быть. В классе должны быть методы и свойства для принятия квитанций, вывода всех имеющихся и собственно хранения всех квитанций.

Названия всех классов должны начинаться с большой буквы. Названия методов/функций должно отражать то, что они делают. Проверьте правильность написания названий классов, методов, файлов через переводчик.

Также добавить файл .gitignore в котором убрать папку .idea

2022-04-08 21:21 UTC, Garik77770 commented
@DenVilk  Изменил в файл workshop.py сделал результат квитанций, а сам код квитанций в файле kvitancia.py или по другому нужно

2022-04-09 13:49 UTC, DenVilk requested changes
Классы ```Date``` и ```Status``` должны быть атрибутами класса ```Reciept```, а не классами.

Файл ```Workshop.py``` хранит в себе что-то непонятное. 
У нас основной класс, с которым мы будем работать везде это ```Reciept```. Класс ```Workshop``` реализовывать не обязательно.

Поля класса ```Reciept``` указаны в ТЗ. У вас должно быть написано не меньше чем в тз.

2022-04-09 13:49 UTC, DenVilk commented on kvitancia.py
> +class Receip:
Проверьте название класса в переводчике.

2022-04-09 13:49 UTC, DenVilk commented on kvitancia.py
> +        import random
Лучше выносить import в начало модуля.

2022-04-11 08:07 UTC, Garik77770 commented
@DenVilk  Внес изменения

2022-04-14 16:52 UTC, DenVilk requested changes
Docstring должны располагаться после строки объявления метода.
Классы ```Vibor```, ```Name``` убрать. Проверить названия функций и переменных.
Переопределить метод строкового представления (\_\_str\_\_()) для всех классов.

Ввод информации об устройствах происходит вне класса:
- Сначала читаем информацию. 
- Создаем объект устройства
- Создаем объект квитанции

2022-04-14 16:52 UTC, DenVilk commented on main.py
> +from technic import Telephon
from technic import (...)

2022-04-15 08:17 UTC, Garik77770 commented
@DenVilk  Я переписал код под ваши замечания

2022-04-16 12:11 UTC, DenVilk approved these changes
Допущен к выполнению второго уровня.

2022-04-17 18:58 UTC, merged